import pyrebase

firebaseConfig = {
    "apiKey": "AIzaSyBNaKi51fnAdaJkSdUz3BTLmQ8U-C427HU",
    "authDomain": "boletimcorona-91d5c.firebaseapp.com",
    "databaseURL": "https://boletimcorona-91d5c.firebaseio.com",
    "projectId": "boletimcorona-91d5c",
    "storageBucket": "boletimcorona-91d5c.appspot.com",
    "messagingSenderId": "555049472129",
    "appId": "1:555049472129:web:dd39192adc6f1742bb7d80"
}

firebase = pyrebase.initialize_app(firebaseConfig)
db = firebase.database()

br1 = db.child("boletimcorona-91d5c").child("estados/br/confirm-br").get()
casosconfirmadosbr = br1.val()
br2 = db.child("boletimcorona-91d5c").child("estados/br/suspeit-br").get()
casossuspeitosbr = br2.val()
br3 = db.child("boletimcorona-91d5c").child("estados/br/mortes-br").get()
mortesbr = br3.val()
br4 = db.child("boletimcorona-91d5c").child("estados/br/data-br").get()
databr = br4.val()

df1 = db.child("boletimcorona-91d5c").child("estados/df/confirm-df").get()
casosconfirmadosdf = df1.val()
df2 = db.child("boletimcorona-91d5c").child("estados/df/suspeit-df").get()
casossuspeitosdf = df2.val()
df3 = db.child("boletimcorona-91d5c").child("estados/df/mortes-df").get()
mortesdf = df3.val()
df4 = db.child("boletimcorona-91d5c").child("estados/df/data-df").get()
datadf = df4.val()

ac1 = db.child("boletimcorona-91d5c").child("estados/ac/confirm-ac").get()
casosconfirmadosac = ac1.val()
ac2 = db.child("boletimcorona-91d5c").child("estados/ac/suspeit-ac").get()
casossuspeitosac = ac2.val()
ac3 = db.child("boletimcorona-91d5c").child("estados/ac/mortes-ac").get()
mortesac = ac3.val()
ac4 = db.child("boletimcorona-91d5c").child("estados/ac/data-ac").get()
dataac = ac4.val()

al1 = db.child("boletimcorona-91d5c").child("estados/al/confirm-al").get()
casosconfirmadosal = al1.val()
al2 = db.child("boletimcorona-91d5c").child("estados/al/suspeit-al").get()
casossuspeitosal = al2.val()
al3 = db.child("boletimcorona-91d5c").child("estados/al/mortes-al").get()
mortesal = al3.val()
al4 = db.child("boletimcorona-91d5c").child("estados/al/data-al").get()
dataal = al4.val()

am1 = db.child("boletimcorona-91d5c").child("estados/am/confirm-am").get()
casosconfirmadosam = am1.val()
am2 = db.child("boletimcorona-91d5c").child("estados/am/suspeit-am").get()
casossuspeitosam = am2.val()
am3 = db.child("boletimcorona-91d5c").child("estados/am/mortes-am").get()
mortesam = am3.val()
am4 = db.child("boletimcorona-91d5c").child("estados/am/data-am").get()
dataam = am4.val()

amp1 = db.child("boletimcorona-91d5c").child("estados/amp/confirm-amp").get()
casosconfirmadosamp = amp1.val()
amp2 = db.child("boletimcorona-91d5c").child("estados/amp/suspeit-amp").get()
casossuspeitosamp = amp2.val()
amp3 = db.child("boletimcorona-91d5c").child("estados/amp/mortes-amp").get()
mortesamp = amp3.val()
amp4 = db.child("boletimcorona-91d5c").child("estados/amp/data-amp").get()
dataamp = amp4.val()

ba1 = db.child("boletimcorona-91d5c").child("estados/ba/confirm-ba").get()
casosconfirmadosba = ba1.val()
ba2 = db.child("boletimcorona-91d5c").child("estados/ba/suspeit-ba").get()
casossuspeitosba = ba2.val()
ba3 = db.child("boletimcorona-91d5c").child("estados/ba/mortes-ba").get()
mortesba = ba3.val()
ba4 = db.child("boletimcorona-91d5c").child("estados/ba/data-ba").get()
databa = ba4.val()

ce1 = db.child("boletimcorona-91d5c").child("estados/ce/confirm-ce").get()
casosconfirmadosce = ce1.val()
ce2 = db.child("boletimcorona-91d5c").child("estados/ce/suspeit-ce").get()
casossuspeitosce = ce2.val()
ce3 = db.child("boletimcorona-91d5c").child("estados/ce/mortes-ce").get()
mortesce = ce3.val()
ce4 = db.child("boletimcorona-91d5c").child("estados/ce/data-ce").get()
datace = ce4.val()

es1 = db.child("boletimcorona-91d5c").child("estados/es/confirm-es").get()
casosconfirmadoses = es1.val()
es2 = db.child("boletimcorona-91d5c").child("estados/es/suspeit-es").get()
casossuspeitoses = es2.val()
es3 = db.child("boletimcorona-91d5c").child("estados/es/mortes-es").get()
morteses = es3.val()
es4 = db.child("boletimcorona-91d5c").child("estados/es/data-es").get()
dataes = es4.val()

go1 = db.child("boletimcorona-91d5c").child("estados/go/confirm-go").get()
casosconfirmadosgo = go1.val()
go2 = db.child("boletimcorona-91d5c").child("estados/go/suspeit-go").get()
casossuspeitosgo = go2.val()
go3 = db.child("boletimcorona-91d5c").child("estados/go/mortes-go").get()
mortesgo = go3.val()
go4 = db.child("boletimcorona-91d5c").child("estados/go/data-go").get()
datago = go4.val()

ma1 = db.child("boletimcorona-91d5c").child("estados/ma/confirm-ma").get()
casosconfirmadosma = ma1.val()
ma2 = db.child("boletimcorona-91d5c").child("estados/ma/suspeit-ma").get()
casossuspeitosma = ma2.val()
ma3 = db.child("boletimcorona-91d5c").child("estados/ma/mortes-ma").get()
mortesma = ma3.val()
ma4 = db.child("boletimcorona-91d5c").child("estados/ma/data-ma").get()
datama = ma4.val()

mg1 = db.child("boletimcorona-91d5c").child("estados/mg/confirm-mg").get()
casosconfirmadosmg = mg1.val()
mg2 = db.child("boletimcorona-91d5c").child("estados/mg/suspeit-mg").get()
casossuspeitosmg = mg2.val()
mg3 = db.child("boletimcorona-91d5c").child("estados/mg/mortes-mg").get()
mortesmg = mg3.val()
mg4 = db.child("boletimcorona-91d5c").child("estados/mg/data-mg").get()
datamg = mg4.val()

mt1 = db.child("boletimcorona-91d5c").child("estados/mt/confirm-mt").get()
casosconfirmadosmt = mt1.val()
mt2 = db.child("boletimcorona-91d5c").child("estados/mt/suspeit-mt").get()
casossuspeitosmt = mt2.val()
mt3 = db.child("boletimcorona-91d5c").child("estados/mt/mortes-mt").get()
mortesmt = mt3.val()
mt4 = db.child("boletimcorona-91d5c").child("estados/mt/data-mt").get()
datamt = mt4.val()

mtsul1 = db.child("boletimcorona-91d5c").child("estados/mtsul/confirm-mtsul").get()
casosconfirmadosmtsul = mtsul1.val()
mtsul2 = db.child("boletimcorona-91d5c").child("estados/mtsul/suspeit-mtsul").get()
casossuspeitosmtsul = mtsul2.val()
mtsul3 = db.child("boletimcorona-91d5c").child("estados/mtsul/mortes-mtsul").get()
mortesmtsul = mtsul3.val()
mtsul4 = db.child("boletimcorona-91d5c").child("estados/mtsul/data-mtsul").get()
datamtsul = mtsul4.val()

para1 = db.child("boletimcorona-91d5c").child("estados/para/confirm-para").get()
casosconfirmadospara = para1.val()
para2 = db.child("boletimcorona-91d5c").child("estados/para/suspeit-para").get()
casossuspeitospara = para2.val()
para3 = db.child("boletimcorona-91d5c").child("estados/para/mortes-para").get()
mortespara = para3.val()
para4 = db.child("boletimcorona-91d5c").child("estados/para/data-para").get()
datapara = para4.val()

pb1 = db.child("boletimcorona-91d5c").child("estados/pb/confirm-pb").get()
casosconfirmadospb = pb1.val()
pb2 = db.child("boletimcorona-91d5c").child("estados/pb/suspeit-pb").get()
casossuspeitospb = pb2.val()
pb3 = db.child("boletimcorona-91d5c").child("estados/pb/mortes-pb").get()
mortespb = pb3.val()
pb4 = db.child("boletimcorona-91d5c").child("estados/pb/data-pb").get()
datapb = pb4.val()

pe1 = db.child("boletimcorona-91d5c").child("estados/pe/confirm-pe").get()
casosconfirmadospe = pe1.val()
pe2 = db.child("boletimcorona-91d5c").child("estados/pe/suspeit-pe").get()
casossuspeitospe = pe2.val()
pe3 = db.child("boletimcorona-91d5c").child("estados/pe/mortes-pe").get()
mortespe = pe3.val()
pe4 = db.child("boletimcorona-91d5c").child("estados/pe/data-pe").get()
datape = pe4.val()

pi1 = db.child("boletimcorona-91d5c").child("estados/pi/confirm-pi").get()
casosconfirmadospi = pi1.val()
pi2 = db.child("boletimcorona-91d5c").child("estados/pi/suspeit-pi").get()
casossuspeitospi = pi2.val()
pi3 = db.child("boletimcorona-91d5c").child("estados/pi/mortes-pi").get()
mortespi = pi3.val()
pi4 = db.child("boletimcorona-91d5c").child("estados/pi/data-pi").get()
datapi = pi4.val()

pr1 = db.child("boletimcorona-91d5c").child("estados/pr/confirm-pr").get()
casosconfirmadospr = pr1.val()
pr2 = db.child("boletimcorona-91d5c").child("estados/pr/suspeit-pr").get()
casossuspeitospr = pr2.val()
pr3 = db.child("boletimcorona-91d5c").child("estados/pr/mortes-pr").get()
mortespr = pr3.val()
pr4 = db.child("boletimcorona-91d5c").child("estados/pr/data-pr").get()
datapr = pr4.val()

rj1 = db.child("boletimcorona-91d5c").child("estados/rj/confirm-rj").get()
casosconfirmadosrj = rj1.val()
rj2 = db.child("boletimcorona-91d5c").child("estados/rj/suspeit-rj").get()
casossuspeitosrj = rj2.val()
rj3 = db.child("boletimcorona-91d5c").child("estados/rj/mortes-rj").get()
mortesrj = rj3.val()
rj4 = db.child("boletimcorona-91d5c").child("estados/rj/data-rj").get()
datarj = rj4.val()

rn1 = db.child("boletimcorona-91d5c").child("estados/rn/confirm-rn").get()
casosconfirmadosrn = rn1.val()
rn2 = db.child("boletimcorona-91d5c").child("estados/rn/suspeit-rn").get()
casossuspeitosrn = rn2.val()
rn3 = db.child("boletimcorona-91d5c").child("estados/rn/mortes-rn").get()
mortesrn = rn3.val()
rn4 = db.child("boletimcorona-91d5c").child("estados/rn/data-rn").get()
datarn = rn4.val()

ron1 = db.child("boletimcorona-91d5c").child("estados/ron/confirm-ron").get()
casosconfirmadosron = ron1.val()
ron2 = db.child("boletimcorona-91d5c").child("estados/ron/suspeit-ron").get()
casossuspeitosron = ron2.val()
ron3 = db.child("boletimcorona-91d5c").child("estados/ron/mortes-ron").get()
mortesron = ron3.val()
ron4 = db.child("boletimcorona-91d5c").child("estados/ron/data-ron").get()
dataron = ron4.val()

rora1 = db.child("boletimcorona-91d5c").child("estados/rora/confirm-rora").get()
casosconfirmadosrora = rora1.val()
rora2 = db.child("boletimcorona-91d5c").child("estados/rora/suspeit-rora").get()
casossuspeitosrora = rora2.val()
rora3 = db.child("boletimcorona-91d5c").child("estados/rora/mortes-rora").get()
mortesrora = rora3.val()
rora4 = db.child("boletimcorona-91d5c").child("estados/rora/data-rora").get()
datarora = rora4.val()

rs1 = db.child("boletimcorona-91d5c").child("estados/rs/confirm-rs").get()
casosconfirmadosrs = rs1.val()
rs2 = db.child("boletimcorona-91d5c").child("estados/rs/suspeit-rs").get()
casossuspeitosrs = rs2.val()
rs3 = db.child("boletimcorona-91d5c").child("estados/rs/mortes-rs").get()
mortesrs = rs3.val()
rs4 = db.child("boletimcorona-91d5c").child("estados/rs/data-rs").get()
datars = rs4.val()

sc1 = db.child("boletimcorona-91d5c").child("estados/sc/confirm-sc").get()
casosconfirmadossc = sc1.val()
sc2 = db.child("boletimcorona-91d5c").child("estados/sc/suspeit-sc").get()
casossuspeitossc = sc2.val()
sc3 = db.child("boletimcorona-91d5c").child("estados/sc/mortes-sc").get()
mortessc = sc3.val()
sc4 = db.child("boletimcorona-91d5c").child("estados/sc/data-sc").get()
datasc = sc4.val()

se1 = db.child("boletimcorona-91d5c").child("estados/se/confirm-se").get()
casosconfirmadosse = se1.val()
se2 = db.child("boletimcorona-91d5c").child("estados/se/suspeit-se").get()
casossuspeitosse = se2.val()
se3 = db.child("boletimcorona-91d5c").child("estados/se/mortes-se").get()
mortesse = se3.val()
se4 = db.child("boletimcorona-91d5c").child("estados/se/data-se").get()
datase = se4.val()

sp1 = db.child("boletimcorona-91d5c").child("estados/sp/confirm-sp").get()
casosconfirmadossp = sp1.val()
sp2 = db.child("boletimcorona-91d5c").child("estados/sp/suspeit-sp").get()
casossuspeitossp = sp2.val()
sp3 = db.child("boletimcorona-91d5c").child("estados/sp/mortes-sp").get()
mortessp = sp3.val()
sp4 = db.child("boletimcorona-91d5c").child("estados/sp/data-sp").get()
datasp = sp4.val()

to1 = db.child("boletimcorona-91d5c").child("estados/to/confirm-to").get()
casosconfirmadosto = to1.val()
to2 = db.child("boletimcorona-91d5c").child("estados/to/suspeit-to").get()
casossuspeitosto = to2.val()
to3 = db.child("boletimcorona-91d5c").child("estados/to/mortes-to").get()
mortesto = to3.val()
to4 = db.child("boletimcorona-91d5c").child("estados/to/data-to").get()
datato = to4.val()






